# Generated by Django 3.1.4 on 2021-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Rasm'),
        ),
    ]
